/// Flutter icons CompassIcon
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CompassIcon
///      fonts:
///       - asset: fonts/CompassIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CompassIcon {
  CompassIcon._();

  static const _kFontFam = 'CompassIcon';
  static const String? _kFontPkg = null;

  static const IconData major_lines = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minor_lines = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData semi_major_lines = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData needle = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData north_arrow = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData north_direction = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData directions = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
