/// Flutter icons WeatherIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  WeatherIcons
///      fonts:
///       - asset: fonts/WeatherIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class WeatherIcons {
  WeatherIcons._();

  static const _kFontFam = 'WeatherIcons';
  static const String? _kFontPkg = null;

  static const IconData dew_point = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData precipitation = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moon = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snow = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_precipitation = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moon_partly = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rain = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData humidity = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sun_partly = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sun = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_partly = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
